config/routes.rb
Rails.application.routes.draw do
 
  resources :movies
  resources :watch_lists do
    resources :watch_list_movies 
    get "/watch_list_movies/:genre_slug", to: "watch_list_movies#genres" 
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root "welcome#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/watch_list.rb
class WatchList < ApplicationRecord
  belongs_to :user
  has_many :watch_list_movies
  has_many :movies, through: :watch_list_movies
  has_many :watched_movies, -> { where(watch_list_movies: {watched: true}) },
  through: :watch_list_movies, source: :movie
  has_many :unwatched_movies, -> { where(watch_list_movies: {watched: false}) },
  through: :watch_list_movies, source: :movie

  validates :name, presence: true, uniqueness: true

  

end

app/controllers/watch_lists_controller.rb
class WatchListsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_watch_list, only: [:show, :edit, :update, :destroy]
    
    def index
        @watch_lists = current_user.watch_lists
    end

    def show
        @watch_list_movies = set_watch_list.watch_list_movies
    end

    def new
        @watch_list = WatchList.new
    end

    def create
        @watch_list = current_user.watch_lists.build(watch_list_params)

        if @watch_list.save
            redirect_to watch_list_path(@watch_list)
        else
            render :new
        end

    end

    def edit

    end

    def update

        if @watch_list.update(watch_list_params)
            redirect_to watch_list_path(@watch_list)
        else
            render :edit
        end

    end

    def destroy
        @watch_list.watch_list_movies.destroy_all
        @watch_list.destroy
        redirect_to watch_lists_path
    end

    private
    
    def set_watch_list
        @watch_list = current_user.watch_lists.find(params[:id])
    end

    def watch_list_params
        params.require(:watch_list).permit(:name)
    end

end

app/helpers/watch_lists_helper.rb
module WatchListsHelper
end

app/views/watch_lists/_form.html.erb
<%= form_for watch_list do |f| %>
    <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </p>

        <%= f.submit %>
<% end %>

app/views/watch_lists/edit.html.erb
<h1>Edit Watch List</h1>
<%= render partial: 'shared/errors', locals: { object: @watch_list } %>
<%= render partial: 'form', locals: {watch_list: @watch_list} %>

app/views/watch_lists/index.html.erb
<h1><%= current_user.username %>'s Watch Lists</h1>

<% @watch_lists.each do |watch_list| %>
    <%= link_to watch_list.name, watch_list_path(watch_list), class: "text_color" %><br>
<% end %>
<br>

app/views/watch_lists/new.html.erb
<h1>New Watch List</h1>
<%= render partial: 'shared/errors', locals: { object: @watch_list } %>
<%= render partial: 'form', locals: {watch_list: @watch_list} %>

app/views/watch_lists/show.html.erb
<h1><%= @watch_list.name%></h1>

<table style= "width: 500px">
    <tr>
        <th style= "text-align: left">Movies</th>
        <th>Watched</th>
    </tr>
    
    <% @watch_list.movies.each do |movie|%>
        <tr>    
           <td style = "text-align: left"> <%= link_to movie.title, movie_path(movie), class: "text_color" %>
        </td>

        <% @watch_list.watch_list_movies.watched.each do |movie_watched| %>
            <% if movie.id == movie_watched.movie_id %>
                <td style= "text-align: center">&#10004</td>
            <% end %>
        <% end %>

        <% @watch_list.watch_list_movies.unwatched.each do |movie_unwatched| %>
            <% if movie.id == movie_unwatched.movie_id %>
                <td style= "text-align: center"></td>
            <% end %>
        <% end %>
        </tr>
    <% end %>
</table>

<%= form_tag(watch_list_path(@watch_list), method: :delete) do %>
    <%= submit_tag "Delete Watch List", style: "margin-top: 100px;" %>
<% end %>


<div class="options">
    <div class="dropdown">
        <button class="dropbtn" style="color: black;"><strong>Watch List Options</strong>
            <i class="fa fa-caret-down"></i></button>
        <div class="dropdown-content">
            <%= link_to 'Edit Watch List', edit_watch_list_path(@watch_list) %>
            <%= link_to 'Add Watch List Movies', new_watch_list_watch_list_movie_path(@watch_list) %>
            <%= link_to 'Unwatched Movies', watch_list_watch_list_movies_path(@watch_list) %>
        </div>
    </div>
</div>