config/routes.rb
Rails.application.routes.draw do
 
  resources :movies
  resources :watch_lists do
    resources :watch_list_movies 
    get "/watch_list_movies/:genre_slug", to: "watch_list_movies#genres" 
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root "welcome#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CinemateAppRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='navbar'>
        <%= link_to "Home", root_path %>
        <div class="dropdown">
          <button class="dropbtn">Movies
            <i class="fa fa-caret-down"></i></button>
          <div class="dropdown-content">
              <%= link_to "All Movies", movies_path %>
              <%= link_to "Movie Database", new_movie_path %>
          </div>
        </div>
      <% if user_signed_in? %>
        <div class="dropdown">
          <button class="dropbtn">Watch Lists
            <i class="fa fa-caret-down"></i></button>
            <div class="dropdown-content">
              <%= link_to "Watch Lists", watch_lists_path %>
              <%= link_to "Create Watch List", new_watch_list_path %>
            </div>
        </div>
        <%= form_tag(destroy_user_session_path, method: :delete, style: "display: inline-block;") do %>
         <%= submit_tag "Sign Out", class: "sign_out" %>
        <% end %>
      <% else %>
        <%= link_to "Log In", new_user_session_path %>
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>
    
    <% flash.each do |name, msg| -%>
    <p>
      <%= content_tag :div, msg, class: name %>
    </p>
    <% end -%>
    <%= yield %>
  </body>
</html>